diffusion_model:
  state_dim: 7           # dimensionality of state vector
  hidden_dim: 128        # transformer hidden size
  num_layers: 4          # number of transformer layers
  nhead: 4               # number of attention heads

sampler:
  horizon: 16            # planning horizon
  stride: 1              # jump-step stride

critic:
  model_path: "path/to/critic_model.pt"  # path to trained critic weights
  state_dim: 7          # must match diffusion_model.state_dim
  horizon: 16           # must match sampler.horizon
  hidden_dim: 128       # hidden dimension of critic MLP
  device: "cpu"        # device to load critic on

planner:
  n_samples: 8          # number of candidate trajectories to sample

invdynamics:
  o_dim: 7             # state_dim for inverse dynamics
  a_dim: 3             # action dimensionality
  hidden_dim: 512      # hidden dimension in inverse dynamics MLP
  model_path: "path/to/inv_dyn.pt"  # path to trained inverse dynamics model
  device: "cpu"

training:
  batch_size: 64
  diffusion_lr: 1e-3
  invdyn_lr: 5e-4
  epochs: 10
  repo_id: "lerobot/pusht" # Example dataset, change as needed
  delta_timestamps:
    observation.state: [0.0]
    action: [0.0]
device: "cpu"
dataset_repo_id: lerobot/aloha_sim_insertion_human